WebsiteBanGiay/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanGiay.Context;
using WebsiteBanGiay.Models;

namespace WebsiteBanGiay.Controllers
{
    public class CartController : Controller
    {
        WebsiteBanGiayEntities ojbWebsiteBanGiayEntities = new WebsiteBanGiayEntities();
        // GET: Cart
        public ActionResult Index()
        {
            return View((List<CartModel>)Session["cart"]);
        }
        public ActionResult AddToCart(int id, int quantity)
        {
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Product = ojbWebsiteBanGiayEntities.SanPhams.Find(id), Quantity = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiểm tra sản phẩm có tồn tại trong giỏ hàng chưa???
                int index = isExist(id);
                if (index != -1)
                {
                    //nếu sp tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].Quantity += quantity;
                }
                else
                {
                    //nếu không tồn tại thì thêm sản phẩm vào giỏ hàng
                    cart.Add(new CartModel { Product = ojbWebsiteBanGiayEntities.SanPhams.Find(id), Quantity = quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
        private int isExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Product.ID.Equals(id))
                    return i;
            return -1;
        }
        //xóa sản phẩm khỏi giỏ hàng theo id
        public ActionResult Remove(int Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Product.ID == Id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

    }
}

WebsiteBanGiay/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanGiay.Context;
using WebsiteBanGiay.Models;

namespace WebsiteBanGiay.Controllers
{
    public class CategoryController : Controller
    {
        WebsiteBanGiayEntities ojbWebsiteBanGiayEntities = new WebsiteBanGiayEntities();
        // GET: Category
        public ActionResult Index()
        {
            var ListCategory = ojbWebsiteBanGiayEntities.Categories.ToList();
            return View(ListCategory);
        }
        public ActionResult ProductCategory(int ID)
        {
            CategoryModel ojbCategoryModel = new CategoryModel();
            ojbCategoryModel.ListProduct = ojbWebsiteBanGiayEntities.SanPhams.Where(n=>n.CategoryID == ID).ToList();
            ojbCategoryModel.ListCategory = ojbWebsiteBanGiayEntities.Categories.ToList();
            return View(ojbCategoryModel);
        }
    }
}

WebsiteBanGiay/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Website title - bootstrap html template</title>

    <link href="~/Content/images/favicon.ico" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="~/Scripts/js/jquery-2.0.0.min.js" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="~/Scripts/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link href="~/Content/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="~/Content/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/responsive.css" rel="stylesheet" type="text/css" />

    <!-- custom javascript -->
    <script src="~/Scripts/js/script.js" type="text/javascript"></script>
</head>
<body>

    <header class="section-header">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-2 col-lg-3 col-md-12">
                        <a href="~/Home/Index" class="brand-wrap">
                            <img class="logo" src="~/Content/images/logo-white.png" style="width:250px">
                        </a> <!-- brand-wrap.// -->
                    </div>
                    <div class="col-xl-6 col-lg-5 col-md-6">
                        <form action="#" class="search-header">
                            <div class="input-group w-100">
                                <select class="custom-select border-right" name="category_name">
                                    <option value="">All type</option>
                                    <option value="codex">Special</option>
                                    <option value="comments">Only best</option>
                                    <option value="content">Latest</option>
                                </select>
                                <input type="text" class="form-control" placeholder="Search">

                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">
                                        <i class="fa fa-search"></i> Search
                                    </button>
                                </div>
                            </div>
                        </form> <!-- search-wrap .end// -->
                    </div> <!-- col.// -->
                    <div class="col-xl-4 col-lg-4 col-md-6">
                        <div class="widgets-wrap float-md-right">
                            <div class="widget-header mr-3">
                                <a href="#" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-user"></i>
                                        <span class="notify">3</span>
                                    </div>
                                    @if (Session["idUser"] != null)
                                    {
                                        <li><a href="~/Admin/Product/Index">Trang quản trị</a></li>
                                        <li><a href="~/Home/Logout">Đăng xuất</a></li>
                                    }
                                    else
                                    {
                                        <li><a href="~/Home/Register">Đăng kí</a></li>
                                        <li><a href="~/Home/Login">Đăng nhập</a></li>
                                    }
                                </a>
                            </div>
                            <div class="widget-header mr-3">
                                <a href="#" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-comment-dots"></i>
                                        <span class="notify">1</span>
                                    </div>
                                    <small class="text"> Message </small>
                                </a>
                            </div>
                            <div class="widget-header mr-3">
                                <a href="#" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-store"></i>
                                    </div>
                                    <small class="text"> Orders </small>
                                </a>
                            </div>
                            <div class="widget-header">
                                <a href="@Url.Action("Index","Cart")" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-shopping-cart"></i>
                                        <span class="notify">@Session["count"]</span>
                                    </div>
                                    <small class="text"> Cart </small>
                                </a>
                            </div>
                        </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->


        <nav class="navbar navbar-main navbar-expand-lg border-bottom">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="main_nav">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"> <i class="fa fa-bars text-muted mr-2"></i> Danh mục </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="https://localhost:44358/Category/ProductCategory/1">Điện thoại</a>
                                <a class="dropdown-item" href="https://localhost:44358/Category/ProductCategory/2">Máy tính bản</a>
                                <a class="dropdown-item" href="https://localhost:44358/Category/ProductCategory/3">Laptop</a>
                                <a class="dropdown-item" href="https://localhost:44358/Category/ProductCategory/4">Phụ kiện</a>
                                <a class="dropdown-item" href="https://localhost:44358/Category/ProductCategory/5">Đồng hồ</a>
                                <a class="dropdown-item" href="@Url.Action("Index","Category")">Tất cả danh mục</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Chính sách đổi trả hàng & Giao hàng</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Khuyến mãi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Dịch vụ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Liên hệ</a>
                        </li>
                    </ul>
                </div> <!-- collapse .// -->
            </div> <!-- container .// -->
        </nav>
    </header> <!-- section-header.// -->
    @RenderBody()

    <footer class="section-footer bg-secondary">
        <div class="container">
            <section class="footer-top padding-y-lg text-white">
                <div class="row">
                    <div class="col-md-3 py-3">
                        <img class="img-fluid" src="~/Content/images/items/logo2.png">
                        <p>Tầng 4, Tòa nhà Hanoi Group Số 442 Đội Cấn, P. Cống Vị, Q. Ba Đình, Hà Nội</p>
                        <p>(04) 7308 6880 - (04) 3786 8904</p>
                        <p>support@bizweb.vn</p>
                    </div>
                    <div class="col-md-3 py-3">
                        <h3 class="font20">VỀ CHÚNG TÔI</h3>
                        <ul>
                            <li><a>Giới thiệu</a></li>
                            <li><a>Sản phẩm</a></li>
                            <li><a>Tin tức</a></li>
                            <li><a>Bản đồ</a></li>
                            <li><a>Liên hệ</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 py-3">
                        <h3 class="font20">DỊCH VỤ</h3>
                        <ul>
                            <li><a>Giới thiệu</a></li>
                            <li><a>Sản phẩm</a></li>
                            <li><a>Tin tức</a></li>
                            <li><a>Bản đồ</a></li>
                            <li><a>Liên hệ</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 py-3">
                        <h3 class="font20">LIÊN HỆ</h3>
                        <ul>
                            <li><a>Giới thiệu</a></li>
                            <li><a>Sản phẩm</a></li>
                            <li><a>Tin tức</a></li>
                            <li><a>Bản đồ</a></li>
                            <li><a>Liên hệ</a></li>
                        </ul>
                    </div>
                </div>-->
            </section>	<!-- footer-top.// -->

            <section class="footer-bottom text-center">
                <p class="text-muted"> Báo cáo môn học ASP.NET by Đỗ Ngọc Trí-2118110321 </p>
                <br>
            </section>
        </div><!-- //container -->
    </footer>
    <!-- ========================= FOOTER END // ========================= -->
</body>
</html>